### ISSUE TITLE
Total number of buffers

### ISSUE THREAD

**Issue by juanpabloaj** [millermedeiros/vim-statline#2]
when you [show the number of buffer](https://github.com/millermedeiros/vim-statline/blob/master/plugin/statline.vim#L36).

why don't show the total number of buffers ? 

```
 [2/10]
```

**Comment by millermedeiros** [comment]
one thing that may be weird is that the buffer number may be higher than the total number of buffers - open a few buffers and delete the first ones, if you do `:ls` the last buffer number is probably higher than the total... - the buffer number is important for commands like `:[n]b` so I can't simply list the relative buffer number..

just created a branch `iss2` so you can test it and see if it does make sense.

**Comment by juanpabloaj** [comment]
@millermedeiros with you function for number of buffers I begin a widget for status line.
https://github.com/juanpabloaj/bufferWidget

maybe you are interested in this as submodule.

**Comment by millermedeiros** [comment]
nice! I will take a look when I have some free-time (today is being crazy). cheers.

**Comment by millermedeiros** [comment]
decided to add the number of buffer on the format `[n_buffers:current_buffer]`  (e.g. `[2:7]`, `[2:1]`) since the current buffer number can be higher than the total number of buffers, it also makes more sense to keep the constant value on the left side so it won't affect the text alignment while switching buffers.

**Comment by juanpabloaj** [comment]
ok
